### ISSUE TITLE
Car detection

### ISSUE THREAD

**Issue by jasonmadigan** [asmirnou/watsor#10]
First of all, this is great. Had been waiting on frigate to get GPU support for a while now, but seems to be languishing, and I believe you'd contributed it. The docs for this are significantly better, so I've been looking at switching. I have a pretty good working setup with deepstack currently, but would like some of watsor's functionality (in particular, good Home Assistant integration).

I've got some cameras setup, and all seems to be working well. `person` detection works very well, with low-latency, but for some reason I don't seem to be able to trigger a match for `car` or `truck` with stationary or moving vehicles. My config is pretty sparse:

```
...
# Detect the following labels of the object detection model.
# Optional, can be overwritten per camera.
detect:
  - person:
      confidence: 60
  - car:
  - truck:


# List of cameras and their configurations.
cameras:
  - pumphouse:
      width: 640
      height: 480
      input: rtsp://foo:bar@192.168.1.150:554/Streaming/Channels/2/
...
```

Any pointers?
