### ISSUE TITLE
running on snap images

### ISSUE THREAD

**Issue by scipioni** [asmirnou/watsor#19]
How to grab still images from camera ? 

It is interesting to run on grabbed jpeg single images, not stream video. Every (configured) step in seconds ffmpeg can 
grab an image from camera using http protocol. For example unifi cameras has  http://192.168.2.43/snap.jpeg grabbing url

**Comment by asmirnou** [comment]
To make a video from a single image config FFmpeg [slideshow](https://trac.ffmpeg.org/wiki/Slideshow) using `loop` option. Set input `framerate` to specify a delay to read the subsequent image.

```yaml
      width: 1280
      height: 720
      input: "http://192.168.2.43/snap.jpeg"

      ffmpeg:
        decoder:
          - -hide_banner
          - -loglevel
          -  error
          - -nostdin
          - -loop
          -  1
          - -framerate
          -  1/5
          - -i                   
          - -f
          -  rawvideo
          - -pix_fmt
          -  rgb24
```
